[k3s_servers]
sre-copilot-k3s-1 ansible_host=192.168.100.10

[k3s_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/sre_copilot_ed25519
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q root@65.108.102.155"'
